version: '3'
services:
  chatbot:
    build: .
    environment:
        - ACCESS_TOKEN=5721064969:AAHPpjRTu3PGP_OE54Mnu4jG8D7IVNTSRSo
        - HOST=redis
        - PASSWORD=comp7940passwordlab8
        - REDISPORT=6379
        - POSTGRES_DATABSE=d8lo9ipulmq31b
        - POSTGRES_USER=dlrggmpuyfznjv
        - POSTGRES_PASSWORD=9e6cb5354edb6c3c6c6b4ecf0fa15b7b4c31397adc3f75f37d8417fa74cac98e
        - POSTGRES_HOST=ec2-52-205-45-222.compute-1.amazonaws.com
        - POSTGRES_PORT=5432
    entrypoint: python chatbot.py
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "6379:6379"