name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v2

    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
        script_stop: true
        command_timeout: 200m
        script: |
          cd /home/mystack/chatbot
          git pull
          docker-compose up -d --build -f docker-compose.yaml

    - name: Dump docker logs
      uses: jwalton/gh-docker-logs@v1